# Perceptron netwerk

Auteur: Tijmen Muller (tijmen.muller@hu.nl)

- Studentnummer: 1853447
- Naam: Dominik Enzinger
- Datum: 25.02.2026

Test in dit notebook de werking van je code. Werk onderstaande use cases uit.

* Perceptron
  * Logische NOT-poort
  * Logische AND-poort
  * Logische OR-poort
  * Logische NOR-poort
  * PARTY-poort
* Perceptron netwerk
  * Logische XOR-poort 
  * Half adder
* Perceptron learning rule (PLR)
  * AND
  * XOR
  * Iris dataset

## Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import itertools
import random

import ipytest
ipytest.autoconfig()
import pytest

from sklearn.datasets import load_iris

In [2]:
# Importeer je eigen code
from perceptron_network import Perceptron, PerceptronLayer, PerceptronNetwork
from perceptron_vectorized import PerceptronNetworkVectorized

## Tests

De inputs zijn lijsten van nullen en éénen. Elke input begint met een 1 op index 0. Deze 1 wordt toegevoegd voor de berekening met de bias. De waarde op index 0 van de weights representeerd de bias.

### Perceptron

#### Size mismatch

Test om te kijken of de lijst van inputs even lang is als de lijst van weights.  

In [3]:
%%ipytest
def test_exception_raised():
    """Test if an error is raised if the size of the inputs doesn't equal the size of the weights.
    
    The size of the input is 1 the size of the weights is 2, so the exception should be raised.
    The test will succeed if the exception is raised correctly.
    """
    with pytest.raises(Exception):  # Checks if the exception is raised correctly.
        not_gate_weights = [0.5, -1]
        perceptron = Perceptron(weights=not_gate_weights)
        assert perceptron.output([0]) == 1 
        assert perceptron.output([1]) == 0

.                                                                                            [100%]
1 passed in 0.01s


#### NOT-Gate

In [ ]:
%%ipytest
def test_not_gate():
    """Test if the activation_function of the Perceptron class produces the correct outputs when using weights for a NOT-Gate."""
    not_gate_weights = [0.5, -1]
    perceptron = Perceptron(weights=not_gate_weights)
    assert perceptron.output([1, 0]) == 1
    assert perceptron.output([1, 1]) == 0

.                                                                                            [100%]
1 passed in 0.01s


#### AND-Gate

In [ ]:
%%ipytest
def test_and_gate():
    """Test if the activation_function of the Perceptron class produces the correct outputs when using weights for a AND-Gate."""
    and_gate_weights = [-1, 0.5, 0.5]
    perceptron = Perceptron(weights=and_gate_weights)
    assert perceptron.output([1, 0, 0]) == 0
    assert perceptron.output([1, 0, 1]) == 0
    assert perceptron.output([1, 1, 0]) == 0
    assert perceptron.output([1, 1, 1]) == 1

.                                                                                            [100%]
1 passed in 0.01s


#### OR-Gate

In [ ]:
%%ipytest
def test_or_gate():
    """Test if the activation_function of the Perceptron class produces the correct outputs when using weights for a OR-Gate."""
    or_gate_weights = [-0.5, 0.5, 0.5]
    perceptron = Perceptron(weights=or_gate_weights)
    assert perceptron.output([1, 0, 0]) == 0
    assert perceptron.output([1, 0, 1]) == 1
    assert perceptron.output([1, 1, 0]) == 1
    assert perceptron.output([1, 1, 1]) == 1

.                                                                                            [100%]
1 passed in 0.01s


#### NOR-Gate

In [ ]:
%%ipytest
def test_or_gate():
    """Test if the activation_function of the Perceptron class produces the correct outputs when using weights for a NOR-Gate."""
    or_gate_weights = [0, -1, -1, -1]
    perceptron = Perceptron(weights=or_gate_weights)
    assert perceptron.output([1, 0, 0, 0]) == 1
    assert perceptron.output([1, 1, 0, 0]) == 0
    assert perceptron.output([1, 0, 1, 0]) == 0
    assert perceptron.output([1, 0, 0, 1]) == 0
    assert perceptron.output([1, 1, 1, 0]) == 0
    assert perceptron.output([1, 0, 1, 1]) == 0
    assert perceptron.output([1, 1, 0, 1]) == 0
    assert perceptron.output([1, 1, 1, 1]) == 0

.                                                                                            [100%]
1 passed in 0.01s


#### Uitgebreider Beslissysteem

In [ ]:
%%ipytest
def test_party_perceptron():
    """Test if the activation_function of the Perceptron class produces the correct outputs when using weights from the party example."""
    party_gate_weights = [-0.4, 0.6, 0.3, 0.2]
    perceptron = Perceptron(weights=party_gate_weights)
    assert perceptron.output([1, 0, 0, 0]) == 0
    assert perceptron.output([1, 1, 0, 0]) == 1
    assert perceptron.output([1, 0, 1, 0]) == 0
    assert perceptron.output([1, 0, 0, 1]) == 0
    assert perceptron.output([1, 1, 1, 0]) == 1
    assert perceptron.output([1, 0, 1, 1]) == 1
    assert perceptron.output([1, 1, 0, 1]) == 1
    assert perceptron.output([1, 1, 1, 1]) == 1

.                                                                                            [100%]
1 passed in 0.01s


### Perceptron Netwerk

#### XOR-Gate

In [9]:
%%ipytest
def test_xor_gate():
    """Test if the PerceptronNetwork has the correct output when simulating a XOR-Gate."""
    xor_gate_weights = [[[-1, 1, -0.5], [-1, -0.5, 1]],  # first layer
                        [[-0.5, 0.5, 0.5]]]              # second layer
    xor_network = PerceptronNetwork(xor_gate_weights)
    assert xor_network.output([1, 0, 0]) == [0]
    assert xor_network.output([1, 1, 0]) == [1]
    assert xor_network.output([1, 0, 1]) == [1]
    assert xor_network.output([1, 1, 1]) == [0]

.                                                                                            [100%]
1 passed in 0.01s


#### Half Adder

In [10]:
%%ipytest
def test_half_adder():
    """Test if the PerceptronNetwork has the correct output when simulating a XOR-Gate."""
    half_adder_weights = [[[-1, 1, -0.5], [-1, -0.5, 1], [-1, 0.5, 0.5]],   # first layer
                          [[-0.5, 0, 0, 0.5], [-0.5, 0.5, 0.5, 0]]]         # second layer
    half_adder_network = PerceptronNetwork(half_adder_weights)
    assert half_adder_network.output([1, 0, 0]) == [0, 0]
    assert half_adder_network.output([1, 1, 0]) == [0, 1]
    assert half_adder_network.output([1, 0, 1]) == [0, 1]
    assert half_adder_network.output([1, 1, 1]) == [1, 0]

.                                                                                            [100%]
1 passed in 0.01s


### Perceptron Learning Rule (PLR)

#### AND-Gate

In [11]:
%%ipytest
def test_perceptron_training():
    """Test if a perceptron produces the correct outputs for an AND-gate after training."""
    weights = np.random.rand(3)  # Initialize 3 random weights between 0 and 1.
    training_inputs =  [[1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]]
    targets = [0, 0, 0, 1]
    perceptron = Perceptron(weights)
    perceptron.train(training_inputs, targets)
    assert perceptron.output([1, 0, 0]) == 0
    assert perceptron.output([1, 0, 1]) == 0
    assert perceptron.output([1, 1, 0]) == 0
    assert perceptron.output([1, 1, 1]) == 1

.                                                                                            [100%]
1 passed in 0.01s


#### XOR-Gate

Zoals we al uit de les weten is het niet mogelijk om een XOR-Gate met maar een perceptron te bouwen. Er wordt dus geen oplossing gevonden.

In [12]:
weights = np.random.rand(3)
training_inputs =  [[1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]]
targets = [0, 1, 1, 0]
perceptron = Perceptron(weights)

perceptron.train(training_inputs, targets)
print(perceptron)

Training stopped: No solution found after 10000 passes.
Perceptron: Weights: [ 0.07174758 -0.1499939  -0.05471001]


#### Iris Dataset

In [13]:
# Set random seed
student_number = 1853447
np.random.seed(student_number)

##### Setosa en Versicolor

In [14]:
%%ipytest
def test_perceptron_training():
    """Test if a perceptron produces the correct outputs for the iris dataset after training."""
    iris = load_iris(as_frame=True)
    # Keep the dataset as a useable frame
    iris = iris["frame"]
    # Remove the rows containing virginica
    iris = iris.drop(iris[iris["target"] == 2].index)
    # Rename the columns
    iris = iris.rename(columns={"sepal length (cm)": "sepal_length_cm", "sepal width (cm)": "sepal_width_cm", "petal length (cm)": "petal_length_cm", "petal width (cm)": "petal_width_cm"})
    # Create training dataframe with 80% of the iris data.
    train_df = iris[((iris.index >= 0) & (iris.index <= 39)) | ((iris.index >= 50) & (iris.index <= 89))]
    # Create testing dataframe with 20% of the iris data.
    test_df = iris[((iris.index >= 40) & (iris.index <= 49)) | ((iris.index >= 90) & (iris.index <= 99))]
    # Setup training inputs
    train_inputs_list = [[1, rows.sepal_length_cm, rows.sepal_width_cm, rows.petal_length_cm, rows.petal_width_cm] for _, rows in train_df.iterrows()]
    # Setup training targets
    train_targets_list = [rows.target for _, rows in train_df.iterrows()]
    # Setup testing inputs
    test_inputs_list = [[1, rows.sepal_length_cm, rows.sepal_width_cm, rows.petal_length_cm, rows.petal_width_cm] for _, rows in test_df.iterrows()]
    # Setup testing targets
    test_targets_list = [rows.target for _, rows in test_df.iterrows()]

    weights = np.random.rand(5)
    perceptron = Perceptron(weights)
    perceptron.train(train_inputs_list, train_targets_list)
    for i, test_input in enumerate(test_inputs_list):
        assert perceptron.output(test_input) == test_targets_list[i]

.                                                                                            [100%]
1 passed in 0.02s


In [15]:
iris = load_iris(as_frame=True)
# Keep the dataset as a useable frame
iris = iris["frame"]
# Remove the rows containing virginica
iris = iris.drop(iris[iris["target"] == 2].index)
# Rename the columns
iris = iris.rename(columns={"sepal length (cm)": "sepal_length_cm", "sepal width (cm)": "sepal_width_cm", "petal length (cm)": "petal_length_cm", "petal width (cm)": "petal_width_cm"})
# Create training dataframe with 80% of the iris data.
train_df = iris[((iris.index >= 0) & (iris.index <= 39)) | ((iris.index >= 50) & (iris.index <= 89))]
# Create testing dataframe with 20% of the iris data.
test_df = iris[((iris.index >= 40) & (iris.index <= 49)) | ((iris.index >= 90) & (iris.index <= 99))]
# Setup training inputs
train_inputs_list = [[1, rows.sepal_length_cm, rows.sepal_width_cm, rows.petal_length_cm, rows.petal_width_cm] for _, rows in train_df.iterrows()]
# Setup training targets
train_targets_list = [rows.target for _, rows in train_df.iterrows()]
# Setup testing inputs
test_inputs_list = [[1, rows.sepal_length_cm, rows.sepal_width_cm, rows.petal_length_cm, rows.petal_width_cm] for _, rows in test_df.iterrows()]
# Setup testing targets
test_targets_list = [rows.target for _, rows in test_df.iterrows()]

weights = np.random.rand(5)
perceptron = Perceptron(weights)
perceptron.train(train_inputs_list, train_targets_list)

print(perceptron)

Perceptron: Weights: [ 0.16590748 -0.64451773  0.05017975  0.94445928  1.06497347]


### Gevectoriseerd Perceptron Netwerk

#### Not-Gate

In [ ]:
%%ipytest
def test_not_gate():
    """Test if the vectorized network produces correct outputs for a NOT gate."""
    not_gate_weights = [np.array([0.5, -1])]
    perceptron = PerceptronNetworkVectorized(weight_matrices=not_gate_weights)
    assert perceptron.output(np.array([1, 0])) == 1
    assert perceptron.output(np.array([1, 1])) == 0

.                                                                                            [100%]
1 passed in 0.01s


In [35]:
not_gate_weights = [np.array([0.5, -1])]
print(not_gate_weights)


inputs = np.array([[1], [0]])
print(inputs)

result = not_gate_weights @ inputs
print(result)

print("------------")


perceptron_vectorized = PerceptronNetworkVectorized(weight_matrices=not_gate_weights)

print(perceptron_vectorized.output(inputs))
print(perceptron_vectorized.output(np.array([1, 1])))


[array([ 0.5, -1. ])]
[[1]
 [0]]
[[0.5]]
------------
[1]
0


In [37]:
test = np.array([1, 2, 3])
test.shape

(3,)

In [ ]:
perceptron.test()

0: Should be 0 
1: Should be 1 
[[1 1 1]
 [0 0 0]]
